[project]
name = "tsadmetrics"
version = "1.0.16"
description = "Librería para evaluación de detección de anomalías en series temporales"
license = { file = "LICENSE" }
readme = "README.md"
authors = [
  { name = "Pedro Rafael Velasco Priego", email = "i12veprp@uco.es" },
  { name = "Amelia Zafra Gómez", email = "azafra@uco.es" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "PyYAML"
]
[project.optional-dependencies]
dev = [
    "pytest",
    "scikit-learn",
    "ipython",
    "sphinx",
    "sphinx-rtd-theme",
    "numpydoc",
    "myst-parser"
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["."]
include = ["tsadmetrics*"]
exclude = ["tests*"]
namespaces = false

[tool.setuptools.package-data]
tsadmetrics = ["py.typed", "config/*.yaml"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dynamic]
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: GNU General Public License v3 or later (GPLv3+)",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ]
