- pwf:
    beta: 1.0
- dicec
- pw_auc_roc
- pw_auc_pr
- pak

- paf:
    beta: 1.0
- bpaf:
    beta: 1.0
    w: 1
- swf:
    beta: 1.0
- cf:
    beta: 1.0
- pa_auc_pr
- pa_auc_roc
- rbf:
    beta: 1.0
    p_alpha: 0.5
    r_alpha: 0.5
    p_bias: "flat"
    r_bias: "flat"
    cardinality_mode: "one"

- dtpaf:
    k: 1
    beta: 1.0
- eds
- lsaf:
    ni: 1
    beta: 1.0
- mttd
- nab_score

- adc
- tdir:
    k: 5
- dair:
    k: 5
- wdd:
    k: 5
- pakf:
    k: 0.5
    beta: 1.0
- paklf:
    k: 0.5
    l: 1
    beta: 1.0
- taf:
    beta: 1.0
    alpha: 0.5
    delta: 5
    theta: 0.5
    past_range: false

- add
- etaf:
    theta_p: 0.5
    theta_r: 0.5
- td:
    distance: 0

- aff_f:
    beta: 1.0
- naff_f:
    alpha: 0.0
    beta: 1.0
- pate:
    early: 5
    delay: 5
- pate_f1:
    early: 5
    delay: 5
- ttf:
    t: 5
    beta: 1.0
- vus_pr:
    window: 4
- vus_roc:
    window: 4
